# Generated by Django 4.2.4 on 2023-09-07 03:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_rename_parent_id_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
